services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: pace-mosquitto
    ports:
      - "1883:1883"   # MQTT for your Python code
      - "8083:8083"   # MQTT over WebSockets for the browser
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosqdata:/mosquitto/data
volumes:
  mosqdata: {}
